[workspace]
exclude = [
	"Dependency/Microsoft/Dependency/Editor/cli",
	"Dependency/Microsoft/Dependency/Editor/build/win32",
]
members = [
	"Element/Echo",
	"Element/Maintain",
	"Element/Maintain/Dependency/CodeEditorLand/Dependency/Queue",
	"Element/Mountain",
	"Element/Rest",
	"Element/River",
	"Element/Sun",
]
resolver = "2"

[workspace.dependencies]
prun = { version = "*" }

[workspace.metadata]

[workspace.package]
authors = ["Source 🖋️ Open 👐🏻 <Source/Open@Editor.Land>"]
documentation = "HTTPS://Documentation.Editor.Land"
edition = "2021"
homepage = "HTTPS://Editor.Land/"
license-file = "LICENSE"
publish = false
readme = "README.md"
repository = "https://github.com/CodeEditorLand/Land"
