[workspace]
exclude = [
	"Dependency/Microsoft/Dependency/Editor/cli",
	"Dependency/Tauri/Dependency/Tauri",
	"Dependency/Tauri/Dependency/Tauri/crates/tauri",
]
members = [
	# # Microsoft
	# "Dependency/Microsoft/Dependency/Editor/cli",
	# "Dependency/Microsoft/Dependency/LandDevContainers/containers/rust-postgres/test-project",
	# "Dependency/Microsoft/Dependency/LandDevContainers/containers/rust",
	# "Dependency/Microsoft/Dependency/LandExtensionSamples/wasm-component-model-async",
	# "Dependency/Microsoft/Dependency/LandExtensionSamples/wasm-component-model-resource",
	# "Dependency/Microsoft/Dependency/LandExtensionSamples/wasm-component-model",
	# "Dependency/Microsoft/Dependency/LandExtensionSamples/wasm-language-server/server",
	# "Dependency/Microsoft/Dependency/LandRemoteTryRust",
	# "Dependency/Microsoft/Dependency/LandSecretServiceRs",
	# "Dependency/Microsoft/Dependency/LandWASM/rust-api/rust",
	# "Dependency/Microsoft/Dependency/LandWASM/testbeds/component-model-async",
	# "Dependency/Microsoft/Dependency/LandWASM/testbeds/component-model-performance",
	# "Dependency/Microsoft/Dependency/LandWASM/testbeds/component-model-vscode-2",
	# "Dependency/Microsoft/Dependency/LandWASM/testbeds/component-model-vscode",
	# "Dependency/Microsoft/Dependency/LandWASM/testbeds/component-model",
	# "Dependency/Microsoft/Dependency/LandWASM/testbeds/lsp-rust/server",
	# "Dependency/Microsoft/Dependency/LandWASM/testbeds/rust-threads",
	# "Dependency/Microsoft/Dependency/LandWASM/testbeds/rust",

	# # OXC
	# "Dependency/OXC/Dependency/AriaQuery",
	# "Dependency/OXC/Dependency/BenchJavaScriptParserWrittenInRust",

	# # Rolldown
	# "Dependency/Rolldown/Dependency/StringWizard",
	# "Dependency/Rolldown/Dependency/Testcase",

	# # SWC
	# "Dependency/SWC/Dependency/Ddt",

	# # Tauri
	# "Dependency/Tauri/Dependency/CargoMobile2",
	# "Dependency/Tauri/Dependency/RustICNS",
	# "Dependency/Tauri/Dependency/Soup2RS",
	# "Dependency/Tauri/Dependency/Soup2RS/sys",
	# "Dependency/Tauri/Dependency/TauriInlinerRS",
	# "Dependency/Tauri/Dependency/TauriInvokeHTTP",
	# "Dependency/Tauri/Dependency/TauriInvokeHTTP/examples/vanilla/src-tauri",
	# "Dependency/Tauri/Dependency/TauriPluginApp",
	# "Dependency/Tauri/Dependency/TauriPluginAuthenticator",
	# "Dependency/Tauri/Dependency/TauriPluginAutostart",
	# "Dependency/Tauri/Dependency/TauriPluginCLI",
	# "Dependency/Tauri/Dependency/TauriPluginClipboardManager",
	# "Dependency/Tauri/Dependency/TauriPluginDialog",
	# "Dependency/Tauri/Dependency/TauriPluginFS",
	# "Dependency/Tauri/Dependency/TauriPluginFSExtra",
	# "Dependency/Tauri/Dependency/TauriPluginFSWatch",
	# "Dependency/Tauri/Dependency/TauriPluginGlobalShortCut",
	# "Dependency/Tauri/Dependency/TauriPluginHTTP",
	# "Dependency/Tauri/Dependency/TauriPluginLocalhost",
	# "Dependency/Tauri/Dependency/TauriPluginLog",
	# "Dependency/Tauri/Dependency/TauriPluginNotification",
	# "Dependency/Tauri/Dependency/TauriPluginOS",
	# "Dependency/Tauri/Dependency/TauriPluginPersistedScope",
	# "Dependency/Tauri/Dependency/TauriPluginPositioner",
	# "Dependency/Tauri/Dependency/TauriPluginProcess",
	# "Dependency/Tauri/Dependency/TauriPluginShell",
	# "Dependency/Tauri/Dependency/TauriPluginSingleInstance",
	# "Dependency/Tauri/Dependency/TauriPluginSingleInstance/examples/emit-event/src-tauri",
	# "Dependency/Tauri/Dependency/TauriPluginSingleInstance/examples/vanilla/src-tauri",
	# "Dependency/Tauri/Dependency/TauriPluginSQL",
	# "Dependency/Tauri/Dependency/TauriPluginStore",
	# "Dependency/Tauri/Dependency/TauriPluginStore/examples/AppSettingsManager/src-tauri",
	# "Dependency/Tauri/Dependency/TauriPluginStrongHold",
	# "Dependency/Tauri/Dependency/TauriPluginUpdater",
	# "Dependency/Tauri/Dependency/TauriPluginUpload",
	# "Dependency/Tauri/Dependency/TauriPluginWebSocket",
	# "Dependency/Tauri/Dependency/TauriPluginWebSocket/examples/tauri-app/src-tauri",
	# "Dependency/Tauri/Dependency/TauriPluginWindow",
	# "Dependency/Tauri/Dependency/TauriPluginWindowState",
	# "Dependency/Tauri/Dependency/TauriSearch/packages/scraper",
	# "Dependency/Tauri/Dependency/TauriTheia/src-tauri",
	# "Dependency/Tauri/Dependency/TrayIcon",
	# "Dependency/Tauri/Dependency/WebKit2GTKRS",
	# "Dependency/Tauri/Dependency/WebKit2GTKRS/sys",
	# "Dependency/Tauri/Dependency/WebView",
	# "Dependency/Tauri/Dependency/WebView/examples/todo-yew/todomvc",
	# "Dependency/Tauri/Dependency/WebView/webview-sys",
	# "Dependency/Tauri/Dependency/Win7Notifications",
	# "Dependency/Tauri/Dependency/WindowShadows",
	# "Dependency/Tauri/Dependency/WindowShadows/examples/tauri/src-tauri",
	# "Dependency/Tauri/Dependency/WindowVibrancy",
	# "Dependency/Tauri/Dependency/WindowVibrancy/examples/tauri/src-tauri",
	# "Dependency/Tauri/Dependency/Winit",
	# "Dependency/Tauri/Dependency/WinRes",
	# "Dependency/Tauri/Dependency/WinRes/example",
	# "Dependency/Tauri/Dependency/WinRTNotification",
	# "Dependency/Tauri/Dependency/WryMobile",

	# Element
	# "Element/Document",
	# "Element/Maintain",
	# "Element/Maintain/Dependency/CodeEditorLand/Dependency/Queue",

	# "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/autostart",
	# "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/cli",
	# "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/clipboard-manager",
	# "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/deep-link",
	# "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/dialog",
	# "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/fs",
	# "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/global-shortcut",
	# "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/http",
	# "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/log",
	# "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/notification",
	# "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/os",
	# "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/process",
	# "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/single-instance",
	# "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/store",
	# "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/upload",
	# "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/websocket",
	# "Dependency/Tauri/Dependency/Tauri/crates/tauri",
	# "Dependency/Tauri/Dependency/Tauri/crates/tauri-plugin",
	# "Dependency/Tauri/Dependency/Tauri/crates/tauri-utils",
	# "Dependency/Tauri/Dependency/TauriPluginAuthenticator",

	"Element/Common",
	"Element/Echo",
	"Element/Maintain",
	"Element/Mountain",
	# "Element/Rest",
	"Element/River",
	"Element/Sun",
]
resolver = "2"

[workspace.dependencies]
prun = { version = "*" }

Echo = { path = "Element/Echo" }

# Tauri (Mountain)
# tauri = { path = "Dependency/Tauri/Dependency/Tauri/crates/tauri" }
# tauri-plugin-authenticator = { path = "Dependency/Tauri/Dependency/TauriPluginAuthenticator" }
# tauri-plugin-autostart = { path = "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/autostart" }
# tauri-plugin-cli = { path = "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/cli" }
# tauri-plugin-clipboard-manager = { path = "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/clipboard-manager" }
# tauri-plugin-dialog = { path = "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/dialog" }
# tauri-plugin-fs = { path = "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/fs" }
# tauri-plugin-global-shortcut = { path = "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/global-shortcut" }
# tauri-plugin-http = { path = "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/http" }
# tauri-plugin-log = { path = "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/log" }
# tauri-plugin-notification = { path = "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/notification" }
# tauri-plugin-os = { path = "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/os" }
# tauri-plugin-process = { path = "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/process" }
# tauri-plugin-single-instance = { path = "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/single-instance" }
# tauri-plugin-store = { path = "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/store" }
# tauri-plugin-upload = { path = "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/upload" }
# tauri-plugin-websocket = { path = "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/websocket" }
# tauri-plugin-deep-link = { path = "Dependency/Tauri/Dependency/PluginsWorkspace/plugins/deep-link" }

# Global (Mountain, Tauri)
# log = { version = "0.4.27" }
futures = { version = "0.3.31" }
portpicker = { version = "0.1.1" }
regex = { version = "1.11.1" }
unbug = { version = "0.4.0" }

# thiserror = { version = "2.0.12" }
# dunce = { version = "1.0.5" }
# tokio = { version = "1.44.1", features = ["sync", "time", "macros"] }
# tracing = { version = "0.1.41" }
# zbus = { version = "5.5.0" }
# tauri-utils = { path = "Dependency/Tauri/Dependency/Tauri/crates/tauri-utils" }
# url = { version = "2.5.4" }
# glob = { version = "0.3.2" }
# schemars = { version = "0.8.22" }

# Build Dependencies (Mountain, Tauri, Plugin)
# tauri-plugin = { path = "Dependency/Tauri/Dependency/Tauri/crates/tauri-plugin" }

async-trait = { version = "0.1.88" }
base64 = { version = "0.22.1" }
chrono = { version = "0.4.41" }
colored = { version = "3.0.0" }
dirs = { version = "6.0.0" }
env_logger = { version = "0.11.8" }
futures-util = { version = "0.3.31" }
globset = { version = "0.4.16" }
ignore = { version = "0.4.23" }
json5 = { version = "0.4.1" }
keyring = { version = "3.6.2" }
log = { version = "0.4.27" }
once_cell = { version = "1.21.3" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140" }
tauri-build = { version = "2.2.0" }
thiserror = { version = "2.0.12" }
tokio = { version = "1.45.1" }
tokio-tungstenite = { version = "0.26.2" }
toml = { version = "0.8.22" }
toml_edit = { version = "0.22.26" }
url = { version = "2.5.4" }
uuid = { version = "1.17.0" }
clap = { version = "4.5.39", features = ["derive", "env"] }

tauri-plugin-dialog = { version = "2.2.2" }

[workspace.metadata]

[workspace.package]
authors = ["Source 🖋️ Open 👐🏻 <Source/Open@Editor.Land>"]
categories = []
documentation = "https://Documentation.Editor.Land"
edition = "2024"
homepage = "https://Editor.Land/"
license-file = "LICENSE"
publish = false
readme = "README.md"
repository = "https://github.com/CodeEditorLand/Land"
rust-version = "1.89.0"
