#!/usr/bin/env bash
# Maintain/Transfer/Dependency.sh
#
# 1. Dynamically discovers all repos under Land/Dependency/**/.gitmodules
# 2. Also transfers a manually-curated REPOS_EXTRA list (forks + related repos
#    not referenced by any .gitmodules)
#
# Usage (run from Land/):
#   chmod +x Maintain/Transfer/Dependency.sh
#   DRY_RUN=1 ./Maintain/Transfer/Dependency.sh   # preview only
#   ./Maintain/Transfer/Dependency.sh             # real run

set -euo pipefail

# ── Configuration ─────────────────────────────────────────────────────────────
SOURCE_ORG="CodeEditorLand"
DEST_ORG="DependencyCodeEditorLand"
DRY_RUN="${DRY_RUN:-0}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAND_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
DEPENDENCY_ROOT="${LAND_ROOT}/Dependency"

FAILED=()
SKIPPED=()
SUCCESS=()

# ── Sanity checks ─────────────────────────────────────────────────────────────
if ! command -v gh &> /dev/null; then
	echo "ERROR: gh CLI not found. Install: https://cli.github.com/" >&2
	exit 1
fi

if ! gh auth status &> /dev/null; then
	echo "ERROR: Not authenticated. Run: gh auth login" >&2
	exit 1
fi

if [[ ! -d "${DEPENDENCY_ROOT}" ]]; then
	echo "ERROR: Dependency directory not found: ${DEPENDENCY_ROOT}" >&2
	echo "       Run: git submodule update --init --recursive -- Dependency" >&2
	exit 1
fi

# ── Manual extras: forks not referenced in any .gitmodules ────────────────────
# Generated by Maintain/List/Fork.sh on 2026-06-07, minus repos already
# covered by the dynamic .gitmodules scan below.
# Remove any line you want to KEEP in CodeEditorLand.
REPOS_EXTRA=(
	# ── OXC ecosystem ─────────────────────────────────────────────────────────
	OXC
	OXCResolver
	OXCAssets
	OXCFuzzParser
	OXCIntellijPlugin
	EslintPluginOxlint
	MirrorsOxlint
	BenchJavaScriptParserWrittenInRust
	BenchJavaScriptLinter
	BenchNodeJSResolver
	JavaScriptParserInRust
	UniCodeID
	UniCodeIDStart

	# ── Biome ecosystem ───────────────────────────────────────────────────────
	Biome
	BiomeLand
	BiomeIntelliJ
	SetupBiome
	PreCommit
	Resources

	# ── Rolldown ecosystem ────────────────────────────────────────────────────
	Rolldown
	RolldownOnDeno
	RolldownPluginNodePolyfills
	RolldownStarterStackblitz
	RolldownViteEcoCi
	Rollup
	Vite
	VitePluginVue
	StringWizard
	Testcase
	Repros
	BenchMarkFiles
	Benchcases
	BenchmarkResultsStorage

	# ── SWC ecosystem ─────────────────────────────────────────────────────────
	SWC
	SWCLoader
	SWCNode
	SWCDev
	SWCPlayground
	SWCify
	SWCSponsorImages
	SWCEcosystemCi
	SWCProject.github.io
	WebSiteSWC
	LandSWCDevtools
	CLI
	Logo
	Helpers
	Book
	Rustdoc
	PluginUtils
	Register
	TsParserTestRef
	ExtraBindings
	Plugins
	PluginExamples
	Pkgs
	Bins
	Bot
	Ddt
	DbgSWC
	Vote
	RawData
	RawGreenData
	CrawlCoreVersion
	NodeSWC
	Jest
	StringCache
	AMDJSTests

	# ── Deno ecosystem ────────────────────────────────────────────────────────
	WASMTime
	ChromiumBuild
	DenoThirdParty
	DecoratorTests
	Test262ParserTests
	TestSuite
	WASIThreads
	WASITestSuite
	GIR
	GIRFile
	AndroidRsGlue
	HTML5LibTests
	GSRestService
	SpringPetClinic
	plugins-workspace
	ESM

	# ── Tauri adjacent ────────────────────────────────────────────────────────
	DiscordUtilsBot

	# ── General / other forks ─────────────────────────────────────────────────
	Babel
	TypeScript
	Turbo
	LLRT
	JavaScript
	Grok
	Commonality
	Metric
	Wil
	Oniguruma
	NRefactory
	NodeGYP
	DebuggerLibs
	Skia
	AriaQuery
	JsonStripComments
	Dependabot
	Progress
	ZSTDSYS
	RustBert
	RustRocksDB
	RocksDB
	Snappy
	Trail
	Data
	Wanix
	WhirlWind
	Mastodon
	OSQuery
	LandJupyterLSPMiddleware
	Copy
	zstd
)

# ── Discover repos dynamically from .gitmodules ───────────────────────────────
echo "Scanning .gitmodules under ${DEPENDENCY_ROOT} ..."

SEEN=""
UNIQUE_REPOS=()

while IFS= read -r gitmodules_file; do
	while IFS= read -r line; do
		line="${line#"${line%%[![:space:]]*}"}"
		if [[ "${line}" =~ ^url[[:space:]]*=[[:space:]]*ssh://git@github\.com/CodeEditorLand/(.+)\.git$ ]]; then
			repo="${BASH_REMATCH[1]}"
			case " ${SEEN} " in
				*" ${repo} "*) ;;
				*)
					SEEN="${SEEN} ${repo}"
					UNIQUE_REPOS+=("${repo}")
					;;
			esac
		fi
	done < <(grep -E '^\s*url\s*=\s*ssh://git@github\.com/CodeEditorLand/' \
		"${gitmodules_file}" 2> /dev/null || true)
done < <(find "${DEPENDENCY_ROOT}" -name ".gitmodules" -type f | sort)

# ── Merge REPOS_EXTRA (deduped) ───────────────────────────────────────────────
for repo in "${REPOS_EXTRA[@]}"; do
	case " ${SEEN} " in
		*" ${repo} "*) ;;
		*)
			SEEN="${SEEN} ${repo}"
			UNIQUE_REPOS+=("${repo}")
			;;
	esac
done

echo "=================================================================="
echo "  CodeEditorLand → DependencyCodeEditorLand"
echo "=================================================================="
echo "  Source org  : ${SOURCE_ORG}"
echo "  Dest org    : ${DEST_ORG}"
echo "  Repos total : ${#UNIQUE_REPOS[@]}"
echo "  Dry run     : ${DRY_RUN}"
echo ""
echo "  Auto-discovered : from Land/Dependency/**/.gitmodules"
echo "  Manual extras   : REPOS_EXTRA (forks + related)"
echo "=================================================================="
echo ""

if [[ ${#UNIQUE_REPOS[@]} -eq 0 ]]; then
	echo "ERROR: No repos discovered." >&2
	exit 1
fi

# ── Transfer function ─────────────────────────────────────────────────────────
transfer_repo() {
	local REPO="$1"
	local FULL="${SOURCE_ORG}/${REPO}"

	if ! gh repo view "${FULL}" &> /dev/null 2>&1; then
		printf "  [SKIP]  %-60s not found / no access\n" "${REPO}"
		SKIPPED+=("${REPO}")
		return
	fi

	if gh repo view "${DEST_ORG}/${REPO}" &> /dev/null 2>&1; then
		printf "  [SKIP]  %-60s already in %s\n" "${REPO}" "${DEST_ORG}"
		SKIPPED+=("${REPO}")
		return
	fi

	if [[ "${DRY_RUN}" == "1" ]]; then
		printf "  [DRY]   %-60s would transfer\n" "${REPO}"
		SUCCESS+=("${REPO}")
		return
	fi

	printf "  [XFER]  %-60s ... " "${REPO}"
	if gh api \
		--method POST \
		"repos/${FULL}/transfer" \
		-f "new_owner=${DEST_ORG}" \
		--silent 2> /dev/null; then
		echo "OK"
		SUCCESS+=("${REPO}")
	else
		echo "FAILED"
		FAILED+=("${REPO}")
	fi

	sleep 0.5
}

# ── Transfer ──────────────────────────────────────────────────────────────────
echo "── Transferring ${#UNIQUE_REPOS[@]} repos ───────────────────────────────────────"
for r in "${UNIQUE_REPOS[@]}"; do
	transfer_repo "${r}"
done

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "=================================================================="
echo "  Summary"
echo "=================================================================="
echo "  Transferred : ${#SUCCESS[@]}"
echo "  Skipped     : ${#SKIPPED[@]}"
echo "  Failed      : ${#FAILED[@]}"

if [[ ${#FAILED[@]} -gt 0 ]]; then
	echo ""
	echo "  Failed — retry individually:"
	for r in "${FAILED[@]}"; do
		echo "    gh api --method POST repos/${SOURCE_ORG}/${r}/transfer -f new_owner=${DEST_ORG}"
	done
	exit 1
fi
