#!/usr/bin/env node
/**
 * LAND-PATCH: cross-Element product identity fan-out.
 *
 * Reads the authoritative Land product config from
 * `Element/Sky/Public/product.json` (generated by
 * `Maintain/Script/ResolveProductConfig.sh` from .env.Land Product* vars)
 * and writes derived artefacts to every Element that needs them:
 *
 *   1. Element/Sky/Source/Function/Generated/ProductIdentity.ts
 *      - Typed constants every TypeScript consumer imports instead of
 *        hardcoding "FIDDEE", "1.118.0", etc.
 *
 *   2. Element/Mountain/Target/<profile>/product.json  (via copy)
 *      - The product.json that Mountain's main process embeds.
 *
 *   3. Element/Sky/Target/product.json  (via copy)
 *
 *   4. Element/Output/Target/product.json  (via copy)
 *      - So the Output pipeline can consume it during transforms.
 *
 * Idempotent: writes only when the generated content differs from disk.
 * Run from `pnpm Codegen:ResolveIdentity`, the `prepublishOnly` chain,
 * or `TierEnvironment.sh` (after ResolveProductConfig.sh).
 *
 * DESIGN PRINCIPLE:
 *   Microsoft source code is NEVER modified. All Land identity data
 *   originates here, in the Land/Element tree. Build scripts that need
 *   product config import these generated modules instead of reading
 *   Dependency/Microsoft/Dependency/Editor/product.json.
 */
import { promises as Filesystem } from "node:fs";
import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// ---------------------------------------------------------------------------
// Resolve the Land repo root from this script's own location
// Maintain/Codegen/ResolveIdentity.ts → Land/
// ---------------------------------------------------------------------------
const RepoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------
const ProductJsonPath = join(
	RepoRoot,
	"Element",
	"Sky",
	"Public",
	"product.json",
);
const GeneratedDir = join(
	RepoRoot,
	"Element",
	"Sky",
	"Source",
	"Function",
	"Generated",
);
const ProductIdentityTsPath = join(GeneratedDir, "ProductIdentity.ts");

const TargetPaths = [
	join(RepoRoot, "Element", "Mountain", "Target", "release", "product.json"),
	join(RepoRoot, "Element", "Mountain", "Target", "debug", "product.json"),
	join(RepoRoot, "Element", "Sky", "Target", "product.json"),
	join(RepoRoot, "Element", "Output", "Target", "product.json"),
	join(RepoRoot, "Target", "release", "product.json"),
	join(RepoRoot, "Target", "debug", "product.json"),
];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** Read a JSON file, returning null on failure. */
async function ReadJson<T>(Path: string): Promise<T | null> {
	try {
		const Raw = await readFile(Path, "utf8");
		return JSON.parse(Raw) as T;
	} catch {
		return null;
	}
}

/** Write a file only if its content differs from what's on disk. */
async function WriteIfChanged(Path: string, Content: string): Promise<boolean> {
	const Existing = await readFile(Path, "utf8").catch(() => "");
	if (Existing === Content) return false;
	await mkdir(dirname(Path), { recursive: true });
	await writeFile(Path, Content);
	return true;
}

// ---------------------------------------------------------------------------
// Types mirroring the product.json shape
// ---------------------------------------------------------------------------
interface LandProduct {
	nameShort: string;
	nameLong: string;
	applicationName: string;
	dataFolderName: string;
	version: string;
	commit: string;
	quality?: string;
	urlProtocol: string;
	serverApplicationName: string;
	embedderIdentifier?: string;
	date?: string;
	licenseName?: string;
	licenseUrl?: string;
	serverDataFolderName?: string;
	darwinBundleIdentifier?: string;
	reportIssueUrl?: string;
	extensionsGallery?: {
		serviceUrl: string;
		itemUrl: string;
		resourceUrlTemplate: string;
	};
	[key: string]: unknown;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
async function Main(): Promise<void> {
	// 1. Read the authoritative product.json
	const Product = await ReadJson<LandProduct>(ProductJsonPath);
	if (!Product) {
		console.error(
			`[ResolveIdentity] FATAL: Cannot read ${ProductJsonPath}\n` +
				"Run Maintain/Script/ResolveProductConfig.sh first, or ensure\n" +
				"TierEnvironment.sh sourced .env.Land before this script.",
		);
		process.exit(1);
	}

	console.log(
		`[ResolveIdentity] Read product.json: ${Product.nameShort} v${Product.version} (commit ${Product.commit})`,
	);

	// 2. Generate ProductIdentity.ts
	const ProductIdentityTs = [
		`// AUTOGENERATED by Maintain/Codegen/ResolveIdentity.ts -- DO NOT EDIT.`,
		`// Single source of truth: Element/Sky/Public/product.json`,
		`//`,
		`// Every TypeScript consumer imports these constants instead of`,
		`// hardcoding identity strings. Build-time consumer:`,
		`//   - Wind's ResolveConfiguration.ts (runtime fetch from /product.json)`,
		`//   - Output plugins that need to reference product identity`,
		`//   - Cocoon's extension host init data`,
		`//`,
		``,
		`/** Short display name (e.g. "FIDDEE") */`,
		`export const ProductNameShort: string = ${JSON.stringify(Product.nameShort)};`,
		``,
		`/** Long display name (e.g. "FIDDEE") */`,
		`export const ProductNameLong: string = ${JSON.stringify(Product.nameLong)};`,
		``,
		`/** Filesystem-safe app name (e.g. "fiddee") */`,
		`export const ProductApplicationName: string = ${JSON.stringify(Product.applicationName)};`,
		``,
		`/** User data folder name (e.g. ".fiddee") */`,
		`export const ProductDataFolderName: string = ${JSON.stringify(Product.dataFolderName)};`,
		``,
		`/** Semver version string (e.g. "1.118.0") */`,
		`export const ProductVersion: string = ${JSON.stringify(Product.version)};`,
		``,
		`/** Build commit hash (e.g. "dev" or a SHA) */`,
		`export const ProductCommit: string = ${JSON.stringify(Product.commit)};`,
		``,
		...(Product.quality !== undefined
			? [
					`/** Release quality ("stable" | "insider" | "development") */`,
					`export const ProductQuality: string = ${JSON.stringify(Product.quality)};`,
					``,
				]
			: []),
		`/** URL protocol scheme (e.g. "fiddee") */`,
		`export const ProductUrlProtocol: string = ${JSON.stringify(Product.urlProtocol)};`,
		``,
		`/** Server application name (e.g. "fiddee-server") */`,
		`export const ProductServerApplicationName: string = ${JSON.stringify(Product.serverApplicationName)};`,
		``,
		...(Product.embedderIdentifier !== undefined
			? [
					`/** Embedder identifier (e.g. "fiddee-desktop") */`,
					`export const ProductEmbedderIdentifier: string = ${JSON.stringify(Product.embedderIdentifier)};`,
					``,
				]
			: []),
		...(Product.darwinBundleIdentifier !== undefined
			? [
					`/** macOS bundle identifier (e.g. "fiddee.editor") */`,
					`export const ProductDarwinBundleIdentifier: string = ${JSON.stringify(Product.darwinBundleIdentifier)};`,
					``,
				]
			: []),
		...(Product.licenseUrl !== undefined
			? [
					`/** License URL */`,
					`export const ProductLicenseUrl: string = ${JSON.stringify(Product.licenseUrl)};`,
					``,
				]
			: []),
		...(Product.reportIssueUrl !== undefined
			? [
					`/** Issue reporting URL */`,
					`export const ProductReportIssueUrl: string = ${JSON.stringify(Product.reportIssueUrl)};`,
					``,
				]
			: []),
		...(Product.serverDataFolderName !== undefined
			? [
					`/** Server data folder name (e.g. ".land-server") */`,
					`export const ProductServerDataFolderName: string = ${JSON.stringify(Product.serverDataFolderName)};`,
					``,
				]
			: []),
		...(Product.extensionsGallery !== undefined
			? [
					`/** Extension gallery configuration */`,
					`export const ProductExtensionsGallery = ${JSON.stringify(Product.extensionsGallery, null, 2)} as const;`,
					``,
				]
			: []),
		``,
		`/** Complete product configuration object */`,
		`export const ProductConfiguration = ${JSON.stringify(Product, null, 2)} as const;`,
		``,
	].join("\n");

	const TsWrote = await WriteIfChanged(
		ProductIdentityTsPath,
		ProductIdentityTs,
	);

	console.log(
		`[ResolveIdentity] types → ${ProductIdentityTsPath} ${TsWrote ? "(updated)" : "(unchanged)"}`,
	);

	// 3. Copy product.json to all target directories
	let Copied = 0;
	let Skipped = 0;
	for (const TargetPath of TargetPaths) {
		try {
			await mkdir(dirname(TargetPath), { recursive: true });
			await copyFile(ProductJsonPath, TargetPath);
			Copied++;
		} catch (Error) {
			Skipped++;
			console.warn(
				`[ResolveIdentity] WARN: could not copy to ${TargetPath}: ${
					Error instanceof Error ? Error.message : String(Error)
				}`,
			);
		}
	}

	console.log(
		`[ResolveIdentity] copies: ${Copied} written, ${Skipped} skipped`,
	);
	console.log(`[ResolveIdentity] ✓ Done`);
}

Main().catch((Error: unknown) => {
	console.error(Error);
	process.exit(1);
});
