#!/usr/bin/env sh
#===============================================================================
# Maintain/Script/ResolveIdentity.sh - Product identity fan-out codegen
#===============================================================================
#
# Reads the authoritative Land product config from
# Element/Sky/Public/product.json (generated by ResolveProductConfig.sh)
# and writes derived artefacts:
#
#   1. Element/Sky/Source/Function/Generated/ProductIdentity.ts
#      - Typed TypeScript constants for build-time imports.
#
#   2. Element/{Mountain,Sky,Output}/Target/<profile>/product.json
#      - product.json copies for every Element that needs it at runtime.
#
# Idempotent — safe to call from any Build.sh before the VS Code build.
#
# Requires: node >= 18
#===============================================================================

set -e

ScriptDir="$(cd "$(dirname "$0")" && pwd)"
LandRoot="$(cd "$ScriptDir/../.." && pwd)"

CodegenScript="$LandRoot/Maintain/Codegen/ResolveIdentity.ts"

if [ ! -f "$CodegenScript" ]; then
	echo "[ResolveIdentity] WARN: Codegen script not found at $CodegenScript — skipping."
	exit 0
fi

if ! command -v node >/dev/null 2>&1; then
	echo "[ResolveIdentity] node unavailable — skipping."
	exit 0
fi

echo "----------------------------------------"
echo "ResolveIdentity: fan-out product identity"
echo "----------------------------------------"

node "$CodegenScript"

echo "----------------------------------------"
echo "ResolveIdentity: done."
echo "----------------------------------------"
